spring:
  application:
    name: store
  datasource:
    url: jdbc:mysql://localhost:3306/store?createDatabaseIfNotExist=true
    username: root
    password: Adesh@1997
server:
  port: 8080
stripe:
  apiUrl: https://api.stripe.com
  enabled: true
  timeout: 1000
  supported-currencies: INR,USD,EUR,GBP
payment-gateway: stripe
mail:
  host: https://smtp.gmail.com
  port: 5761